{
	"version": 1740486765,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/redlightgreenlighthowto-sheet0.png",
		"images/redlightgreenlighthowto-sheet1.png",
		"images/play-sheet0.png",
		"images/bg-sheet0.png",
		"images/happyface-sheet0.png",
		"images/happyface-sheet1.png",
		"images/usdc-sheet0.png",
		"images/usdc-sheet1.png",
		"images/sprite-sheet0.png",
		"images/particles.png",
		"images/particles2.png",
		"images/ring-sheet0.png",
		"media/tap.m4a",
		"media/tap.ogg",
		"media/game over (4).m4a",
		"media/game over (4).ogg",
		"media/win.m4a",
		"media/win.ogg",
		"media/bg (3).m4a",
		"media/bg (3).ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}